In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from mlxtend.plotting import plot_confusion_matrix
from sklearn import metrics
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import StratifiedShuffleSplit

In [159]:
col_names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
dataset = pd.read_csv("car.data", names=col_names)
dataset.head(5)

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [160]:
# step 1: encode categorical data
# get unique values for each column
buying_values = dataset["buying"].unique()
maint_values = dataset["maint"].unique()
doors_values = dataset["doors"].unique()
persons_values = dataset["persons"].unique()
lug_boot_values = dataset["lug_boot"].unique()
safety_values = dataset["safety"].unique()
class_values = dataset["class"].unique()
print(buying_values)
print(maint_values)
print(doors_values)
print(persons_values)
print(lug_boot_values)
print(safety_values)
print(class_values)

['vhigh' 'high' 'med' 'low']
['vhigh' 'high' 'med' 'low']
['2' '3' '4' '5more']
['2' '4' 'more']
['small' 'med' 'big']
['low' 'med' 'high']
['unacc' 'acc' 'vgood' 'good']


In [161]:
# step 2: create a replace map for each column
buying_replace_map = {buying_values[i]: i for i in range(len(buying_values))}
maint_replace_map = {maint_values[i]: i for i in range(len(maint_values))}
doors_replace_map = {doors_values[i]: i for i in range(len(doors_values))}
persons_replace_map = {persons_values[i]: i for i in range(len(persons_values))}
lug_boot_replace_map = {lug_boot_values[i]: i for i in range(len(lug_boot_values))}
safety_replace_map = {safety_values[i]: i for i in range(len(safety_values))}
class_replace_map = {class_values[i]: i for i in range(len(class_values))}

In [162]:
# step 3: replace each column with the replace map
dataset["buying"] = dataset["buying"].replace(buying_replace_map)
dataset["maint"] = dataset["maint"].replace(maint_replace_map)
dataset["doors"] = dataset["doors"].replace(doors_replace_map)
dataset["persons"] = dataset["persons"].replace(persons_replace_map)
dataset["lug_boot"] = dataset["lug_boot"].replace(lug_boot_replace_map)
dataset["safety"] = dataset["safety"].replace(safety_replace_map)
dataset["class"] = dataset["class"].replace(class_replace_map)

In [163]:
# # step 4: encode the dataset
# ordinal_encoder = OrdinalEncoder()
# dataset = ordinal_encoder.fit_transform(dataset)
# dataset = pd.DataFrame(dataset)
# dataset
print(dataset["buying"].unique())
print(dataset["maint"].unique())
print(dataset["doors"].unique())
print(dataset["persons"].unique())
print(dataset["lug_boot"].unique())
print(dataset["safety"].unique())
print(dataset["class"].unique())

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2 3]


In [164]:
# step 5: split the dataset into training and testing data
X = dataset.drop(["buying", "persons"], axis=1)
y = dataset["buying"]
# X = dataset.drop(columns=[0])
# y = dataset.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [165]:
# step 6: train the model using gini index
model = DecisionTreeClassifier(criterion="gini", max_depth=3, min_samples_split=10)
model.fit(X_train, y_train)

# step 6: train the model using entropy index
model = DecisionTreeClassifier(criterion="entropy", max_depth=3, min_samples_split=10)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, min_samples_split=10)

In [166]:
# step 7: predict the model
y_pred = model.predict(X_test)

In [167]:
# step 8: evaluate the model
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.3044315992292871


In [174]:
# use the replace map to convert the new data point to the same format as the dataset
new_data = ["high", "4", "big", "high", "good"]
new_data_encoded = [maint_replace_map[new_data[0]], doors_replace_map[new_data[1]], lug_boot_replace_map[new_data[2]], safety_replace_map[new_data[3]], class_replace_map[new_data[4]]]
new_data_encoded = np.array(new_data_encoded)
new_data_encoded = new_data_encoded.reshape(1, -1)
new_data_encoded

# predict the new data point
new_data_pred = model.predict(new_data_encoded)
new_data_pred = buying_values[new_data_pred[0]]
print(new_data_pred)

low


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
